name: My test workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo 'Welcome Sof'

        - name: List Files
          run: ls

        - name: Read file
          run: cat README.md